----- SQL ASSIGNMENT 2 -----------

CREATE DATABASE ORDER_STORES_DATA;
USE ORDER_STORES_DATA;

CREATE TABLE ORDERS_TABLE
(
ORDER_DATE DATE,
REGION NVARCHAR(250),
REP NVARCHAR(250),
ORDER_ITEM NVARCHAR(250),
UNITS INT,
UNIT_COST DECIMAL(10,2),
TOTAL_PRICE DECIMAL(10,2),
ORDER_ID INT IDENTITY(1,1) PRIMARY KEY)

SELECT * FROM ORDERS_TABLE
SELECT * FROM STORES_TABLE

-----------------------------------------------------------------------------

CREATE TABLE STORES_TABLE
( STORE_ID INT IDENTITY(1,1) PRIMARY KEY,
STORE_TYPE VARCHAR(250),
ASSORTMENT INT,
COMPETITION_DISTANCE INT,
MONTH_COLUMN INT,
YEAR_COLUMN INT,
PromoInterval NVARCHAR(250))

SELECT * FROM STORES_TABLE
----------------------------------------------------------------------------------
ALTER TABLE STORES_TABLE
ADD STORE_NAMES NVARCHAR(250)

UPDATE ORDERS_TABLE SET ORDER_ITEM = 'COMPASS' WHERE REP = 'GANESH';
UPDATE ORDERS_TABLE SET ORDER_ITEM = 'torch' WHERE REP = 'payal';
UPDATE ORDERS_TABLE SET ORDER_ITEM = 'phone' WHERE REP = 'sorvino';
UPDATE ORDERS_TABLE SET ORDER_ITEM = 'laptop' WHERE REP = 'akshita';
UPDATE ORDERS_TABLE SET ORDER_ITEM = 'box' WHERE REP = 'surbhi';

UPDATE STORES_TABLE SET PromoInterval = 'apr' WHERE STORE_ID = '4';
UPDATE STORES_TABLE SET PromoInterval = 'sep' WHERE STORE_ID = '7';
UPDATE STORES_TABLE SET PromoInterval = 'feb' WHERE STORE_ID = '9';

ALTER TABLE STORES_TABLE
ALTER COLUMN STORE_NOS;

EXEC SP_RENAME 'STORES_TABLE.ASSORTMENT' , 'STORE_NOS', 'COLUMN'

EXEC SP_RENAME 'ORDERS_TABLE.ORDER_ITEM' , 'ITEM_NAME', 'COLUMN'
EXEC SP_RENAME 'ORDERS_TABLE.REP' , 'CUSTOMERS_NAME', 'COLUMN'

SELECT * FROM ORDERS_TABLE ORDER BY UNIT_COST DESC , TOTAL_PRICE ASC;

EXEC SP_RENAME 'ORDERS_TABLE.CUSTOMERS_NAME' , 'CUS_NAME' , 'COLUMN'
SELECT REGION, COUNT(DISTINCT CUS_NAME) AS CUS_COUNT
FROM ORDERS_TABLE
GROUP BY REGION;

SELECT SUM(Total_Price) AS Total_Price_Sum, SUM(UNIT_COST) AS Unit_Cost_Sum
FROM Orders_Table;

CREATE TABLE Order_Stores_table AS
SELECT 
O.ORDER_DATE, O.UNIT_COST, S.STORE_TYPE, S.YEAR_COLUMN 
FROM ORDERS_TABLE AS O
INNER JOIN 
STORES_TABLE  AS S 
ON
O.ORDER_ID = S.STORE_ID

SELECT ITEM_NAME , REGION FROM ORDERS_TABLE WHERE ORDER_ID IN ('4','5','6','9')

SELECT YEAR_COLUMN FROM STORES_TABLE WHERE COMPETITION_DISTANCE IN (29910,310,3160)

SELECT ITEM_NAME FROM Orders_table WHERE Total_Price > 200 AND Total_Price < 400;

EXEC SP_RENAME 'STORES_TABLE.COMPETITION_DISTANCE' , 'CD', 'COLUMN'
SELECT COUNT(*) AS TOTAL_CD
FROM STORES_TABLE

SELECT COUNT(DISTINCT STORE_TYPE) AS TOTAL_STORES_TYPE,
COUNT(DISTINCT CD) AS TOTAL_CD
FROM STORES_TABLE;

SELECT *
FROM Orders_Table
CROSS JOIN Stores_Table;


DROP DATABASE ORDER_STORES_DATA;





